version: '3'
services:
  drivenops-postgres-dev:
    image: postgres:13
    container_name: drivenops-postgres-dev
    restart: always
    env_file:
      - .env.dev
    ports:
      - 1234:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  drivenops-server-dev:
    container_name: drivenops-server-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    depends_on:
      - drivenops-postgres-dev
    env_file:
      - .env.dev
volumes:
  postgres:
