version: '3'
services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.dev
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - database
    env_file:
      - .env.dev
volumes:
  postgres:
