version: '3'
services:
  drivenops-postgres:
    image: postgres:13
    container_name: drivenops-postgres
    restart: always
    ports:
      - 1324:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  drivenops-server:
    container_name: drivenops-server
    build: .
    ports:
      - 5050:5000
    depends_on:
      - drivenops-postgres
    env_file:
      - .env
volumes:
  postgres:
