version: '3'
services:
  drivenops-postgres-test:
    image: postgres:13
    container_name: drivenops-postgres-test
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  drivenops-server-test:
    container_name: drivenops-server-test
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 5000:5000
    depends_on:
      - drivenops-postgres-test
    env_file:
      - .env.test
