name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: ${{ secrets.TEST__POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.TEST__POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.TEST__POSTGRES_DB }}
          envkey_DATABASE_URL: ${{ secrets.TEST__DATABASE_URL }}
          envkey_POSTGRES_PORT: ${{ secrets.TEST__POSTGRES_PORT }}
          envkey_POSTGRES_HOST: ${{ secrets.TEST__POSTGRES_HOST }}
          envkey_NODE_ENV: test
          file_name: .env.test
          working-directory: ${{ env.working-directory }}
      - run: npm run ci:build && npm run ci:test
        working-directory: ${{ env.working-directory }}
